openapi: 3.0.1
info:
  title: Player Games API
  description: API for player games
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /games:
    post:
      summary: Start a new game
      description: Start a new game with the given number
      parameters:
        - in: query
          name: number
          required: true
          schema:
            type: integer
      responses:
        '201':
          description: Game started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonApiResp'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonApiResp'

  /games/{gameId}/moves:
    post:
      summary: Make a move in the game
      description: Make a move in the game with the given ID
      parameters:
        - in: path
          name: gameId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '201':
          description: Move made
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonApiResp'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonApiResp'

  /games/{gameId}:
    get:
      summary: Get current game
      description: Get the current state of the game with the given ID
      parameters:
        - in: path
          name: gameId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Current game
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonApiResp'
        '404':
          description: Game not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonApiResp'
components:
  schemas:
    CommonApiResp:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
        data:
          type: object
          additionalProperties: true
    Game:
      type: object
      properties:
        id:
          type: string
          format: uuid
        number:
          type: integer
        finished:
          type: boolean
        currentPlayer:
          $ref: '#/components/schemas/Player'
        winner:
          $ref: '#/components/schemas/Player'
    Player:
      type: object
      properties:
        name:
          type: string
    Move:
      type: object
      properties:
        player:
          $ref: '#/components/schemas/Player'
        moveValue:
          type: integer
        resultingNumber:
          type: integer
